version: '3'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8080:80
    frontend:
        build:
            context: .
            dockerfile: Dockerfile-backendapp1
        ports: 
            - 8081:80
    backend:
        image: httpd
        volumes: 
            - ./html:/usr/local/apache2/htdocs/